version: '3.9'

services:
  web:
    build: .
    container_name: chatapp
    command: daphne -b 0.0.0.0 -p 8000 mysite.asgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
  redis:
    image: redis:7
    container_name: redis_server
    ports:
      - "6379:6379"
